producer:
  my_account: eos.freezing
  api_address: http://localhost:8888
  secret_p2p_address: localhost:9876
  wallet_address: http://localhost:6666
  block_signing_public_key: EOS8NijGLHT8WyDmt2nqMwfP1hr8EiYx5JCYBWSP9S26WgbeugvSJ
  block_signing_private_key_path: ./privkey-eugvSJ.key

network:
  seed_discovery_url: https://github.com/
  cache_path: /tmp/disco

hooks:
  init:
    exec: ./hooks/init.sh
  start_bios_boot:
    exec: ./hooks/start_bios_boot.sh
  connect_as_abp:
    exec: ./hooks/connect_as_abp.sh
  connect_as_participant:
    exec: ./hooks/connect_as_participant.sh
  publish_kickstart_data:
    exec: ./hooks/publish_kickstart_data.sh
  done:
    exec: ./hooks/done.sh

my_parameters:
  base_per_transaction_net_usage: 100
  base_per_transaction_cpu_usage: 500
  base_per_action_cpu_usage: 1000
  base_setcode_cpu_usage: 2097152  # 2 * 1024 * 1024 // overbilling cpu usage for setcode to cover incidental
  per_signature_cpu_usage: 100000
  per_lock_net_usage: 32
  context_free_discount_cpu_usage_num: 20
  context_free_discount_cpu_usage_den: 100
  max_transaction_cpu_usage: 10485760  # 10 * 1024 * 1024
  max_transaction_net_usage: 102400  # 100 * 1024

  max_block_cpu_usage: 104857600  # 100 * 1024 * 1024; at 500ms blocks and 20000instr trx, this enables ~10,000 TPS burst
  target_block_cpu_usage_pct: 1000  # 10%, 2 decimal places
  max_block_net_usage: 1048576
  target_block_net_usage_pct: 1000  # 10%, 2 decimal places

  max_transaction_lifetime: 3600
  max_transaction_exec_time: 0  # unused?!
  max_authority_depth: 6
  max_inline_depth: 4
  max_inline_action_size: 4096
  max_generated_transaction_count: 16

  max_storage_size: 10485760  # 10 * 1024 * 1024
  percent_of_max_inflation_rate: 10000  # percent, with 2 dec places.
  storage_reserve_ratio: 1000  # ratio * 1000

# ENCRYPTION NOT YET IMPLEMENTED!
pgp:
  program: gpg  # or keybase ?
  path: /usr/bin/gpg  # Make sure your keys are in there.
